id: P29A6B642
initial_creation_type: input
source_metadata:
  title: Ratna Lingpa Series
  language: fr
  description: 'Texts by the famous treasure-revealer Ratna Lingpa (ratna gling pa,
    1403-1479):'
  volume:
    b5246475abd9406e978a1cc895f20c77:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Guru Padmasambhava
    92c8483891a54385bc688c6c14338cac:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Guru Padmasambhava
    a26b3d589df8402c9707ac280c479dab:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Tārā
created_at: '2022-03-01T01:19:45.927966'
last_modified_at: '2022-03-01T01:19:45.927968'
